### ISSUE TITLE
dpr=1 missing?

### ISSUE THREAD

**Issue by maditaly** [gcwelborn/tinder-scraper#13]
I tried to test this today (giving a presentation to High School kids in 2 weeks) but it seems the “access_token” has changed names.. moved on. Anyone have identified where it is placed now to incorporate into tinder-scraper? I found a dpr=2 and found some tokens, but the formatting doesn’t align with what I read in your notes.
Process:
 - followed as described, w/ window showing "FB authorized Tinder - cancel/accept" message ... on this screen I didn't find dpr=1 ... I then clicked "accept" and didn't find dpr=1 in the new traffic.

Much appreciated. Think this will be a fun demonstration if I get it running.

**Comment by gcwelborn** [comment]
@maditaly Can you email me directly @ gcruzwelborn@gmail.com ? I'd be happy to hop on a video chat this weekend and do my best to make sure your presentation goes smoothly.

**Comment by Sobolvitya** [comment]
I faced the same problem today. 
Can you guys post some updates after your discussion please?

**Comment by liamrosen** [comment]
Going to the link specified in my documentation works for me as of today:
https://i.imgur.com/HyelC2t.png

**Comment by maditaly** [comment]
Code is good ... thank you so much Cruz! Sorry I had those basic errors.

**Comment by gcwelborn** [comment]
@maditaly thank **you** for enlightening the next generation on InfoSec, glad to be of help. 

@Sobolvitya if your project is for the greater good of humanity and not personal/corporate gain - feel free to email me directly. Unfortunately I get a significant amount of requests from the latter.
