### ISSUE TITLE
Problem: add Facebook ID and Auth Token

### ISSUE THREAD

**Issue by Sanguinius1** [gcwelborn/tinder-scraper#16]
Hello there! 
I want to conduct an experiment using the tinder scraper.My aim is to find out how people in my area describe themselves in their bios. 

However, i am stuck at step three
#add setup Facebook ID & Auth Token into /lib/config.scraper.js
# using config.example.js as a boilerplate

What exactly is meant with "Facebook ID"? I have found the Auth Token, but am wondering now, how i add these two things in the config.scraper.js

I hope you can help me! 
Kind regards! 
Dominic

**Comment by gcwelborn** [comment]
if you navigate to https://findmyfbid.com/ and input the URL to your facebook profile you should receive your Facebook ID

**Comment by Sanguinius1** [comment]
Thank you very much! I really appreciate your work! :-)
