### ISSUE TITLE
error

### ISSUE THREAD

**Issue by leesander1** [gcwelborn/tinder-scraper#2]
receiving error on npm start

4/5/2016, 11:14:45 PM: attempting to authenticate into tinder...
4/5/2016, 11:14:46 PM: tinder client authorized...
4/5/2016, 11:14:46 PM: Getting new match stack...
4/5/2016, 11:14:46 PM: new match stack received...
4/5/2016, 11:14:46 PM: undefined
4/5/2016, 11:14:46 PM  names of users scraped: C:\Users\leesa\OneDrive\tinder-scraper\app.js:46
      data.results.forEach(function (match) {
                  ^

TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\leesa\OneDrive\tinder-scraper\app.js:46:19
    at Request._callback (C:\Users\leesa\OneDrive\tinder-scraper\node_modules\tinderjs\tinder.js:93:9)
    at Request.self.callback (C:\Users\leesa\OneDrive\tinder-scraper\node_modules\request\request.js:121:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\Users\leesa\OneDrive\tinder-scraper\node_modules\request\request.js:978:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\Users\leesa\OneDrive\tinder-scraper\node_modules\request\request.js:929:12)
    at emitNone (events.js:85:20)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! tinder-scraper@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tinder-scraper@0.0.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tinder-scraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tinder-scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\leesa\OneDrive\tinder-scraper\npm-debug.log

**Comment by gcwelborn** [comment]
are you sure fb_user_token and fb_user_id are correct? if so, it could mean you're not getting any matches. 
Try commenting out lines 45-56 and console.logging the data variable and post the output?

**Comment by leesander1** [comment]
yes the user_token and user_id are correct. I believe it has something to do with the data not binding correctly because it is undefined.

> Try commenting out lines 45-56 and console.logging the data variable and post the output?

4/6/2016, 12:05:38 AM: attempting to authenticate into tinder...
4/6/2016, 12:05:39 AM: tinder client authorized...
4/6/2016, 12:05:39 AM: Getting new match stack...
4/6/2016, 12:05:39 AM: new match stack received...
{ status: '400', error: '' }

and if I run the 
print_timestamped_output(data, 'verbose')
it returns [object Object]

**Comment by gcwelborn** [comment]
Okay, so you're getting a bad request status code.

I haven't tried this library out on windows, but unless the underlying tinder.js library has issues with it I wouldn't worry. maybe @mrmayfield would know about this.

can you try using your info to login to https://tindalytics.herokuapp.com/ and see if your profile loads?

**Comment by leesander1** [comment]
The info loads on the app correctly

**Comment by gcwelborn** [comment]
Made significant changes to tinder-scraper. could you try it out again and see if your error persists?

**Comment by leesander1** [comment]
just tried it out looks like the error I am having still persists

C:\Users\leesa\Downloads\tinder-scraper>npm start

> tinder-scraper@0.0.1 start C:\Users\leesa\Downloads\tinder-scraper
> node app.js

4/10/2016, 11:52:12 PM: attempting to authenticate into tinder...
4/10/2016, 11:52:14 PM: tinder client authorized...
4/10/2016, 11:52:14 PM: ERROR: [object Object]

**Comment by gcwelborn** [comment]
Is it possible to try on a linux distribution or OSX? I'm runnin out of ideas as to why you're able to authenticate in, yet can't request recommendations (potential matches). It's been a while since I used it, but today I spent a couple hours refactoring and making sure it still works.

**Comment by leesander1** [comment]
I'll double check on my Linux partition. yeah it's weird not sure what's
going on.

**Comment by gcwelborn** [comment]
@leesander1 so what happened? did it work on linux? please document your experience so others may benefit from it.
