### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sercotec** [gcwelborn/tinder-scraper#5]
i couldnt make it run as i get 

SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! tinder-scraper@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tinder-scraper@0.0.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the tinder-scraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tinder-scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/serkanerturk/tinder-scraper/npm-debug.log

Error, it might be because of config.js (couldnt figure out how to set it up and json file) can you provide sample files ?

**Comment by gcwelborn** [comment]
what version of node are you running? you can find this by typing `node -v` into your terminal

**Comment by jaafarskafi1** [comment]
worked fine for me (using c9.io IDE)
